version: '3.8'

services:
  django:
    build: .
    container_name: django
    volumes:
      - .:/usr/src/bookstore/
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py makemigrations
             python3 manage.py migrate
             python3 manage.py loaddata fixtures/books.json
             python3 manage.py loaddata fixtures/stores.json
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost, 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DB_HOST=pgdb
      - DB_NAME=bookstore
      - DB_USER=bookstore
      - DB_PASS=bookstore


    depends_on:
      - pgdb
      - redis

  celery:
    build: .
    command: celery -A bookstore worker -l INFO
    volumes:
      - .:/usr/src/bookstore
    depends_on:
      - django
      - pgdb
      - redis
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
  
  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=bookstore
      - POSTGRES_USER=bookstore
      - POSTGRES_PASSWORD=bookstore
    volumes:
      - pgdata:/var/lib/postgresql/data/
    
  redis:
    image: "redis:alpine"

volumes:
  pgdata: