version: '3.8'

services:
  django:
    build: .
    container_name: django
    volumes:
      - .:/usr/src/bookstore/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost, 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DB_HOST=postgres
      - DB_NAME=bookstore
      - DB_USER=bookstore
      - DB_PASS=bookstore
    depends_on:
      - postgres
      - redis

  celery:
    build: .
    command: celery -A bookstore worker -l INFO
    volumes:
      - .:/usr/src/bookstore
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost, 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - django
      - redis
  
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=bookstore
      - POSTGRES_USER=bookstore
      - POSTGRES_PASSWORD=bookstore
    volumes:
      - pgdata:/var/lib/postgresql/data/
    
  redis:
    image: "redis:alpine"

volumes:
  pgdata: