# Generated by Django 5.0.7 on 2024-07-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('city', 'address')},
        ),
    ]
