# Generated by Django 5.0.7 on 2024-08-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='books_quantity',
            field=models.IntegerField(default=0, verbose_name='Количество книг'),
        ),
    ]
